// Code generated by protoc-gen-go. DO NOT EDIT.
// source: generated.proto

package checkpoint

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InputValue struct {
	Period               *int64   `protobuf:"varint,1,req,name=Period" json:"Period,omitempty"`
	PodName              []string `protobuf:"bytes,2,rep,name=PodName" json:"PodName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputValue) Reset()         { *m = InputValue{} }
func (m *InputValue) String() string { return proto.CompactTextString(m) }
func (*InputValue) ProtoMessage()    {}
func (*InputValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ed858329eb171d, []int{0}
}

func (m *InputValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputValue.Unmarshal(m, b)
}
func (m *InputValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputValue.Marshal(b, m, deterministic)
}
func (m *InputValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputValue.Merge(m, src)
}
func (m *InputValue) XXX_Size() int {
	return xxx_messageInfo_InputValue.Size(m)
}
func (m *InputValue) XXX_DiscardUnknown() {
	xxx_messageInfo_InputValue.DiscardUnknown(m)
}

var xxx_messageInfo_InputValue proto.InternalMessageInfo

func (m *InputValue) GetPeriod() int64 {
	if m != nil && m.Period != nil {
		return *m.Period
	}
	return 0
}

func (m *InputValue) GetPodName() []string {
	if m != nil {
		return m.PodName
	}
	return nil
}

type ReturnValue struct {
	Period               *int64   `protobuf:"varint,1,req,name=Period" json:"Period,omitempty"`
	Err                  *string  `protobuf:"bytes,2,req,name=err" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnValue) Reset()         { *m = ReturnValue{} }
func (m *ReturnValue) String() string { return proto.CompactTextString(m) }
func (*ReturnValue) ProtoMessage()    {}
func (*ReturnValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e6ed858329eb171d, []int{1}
}

func (m *ReturnValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnValue.Unmarshal(m, b)
}
func (m *ReturnValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnValue.Marshal(b, m, deterministic)
}
func (m *ReturnValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnValue.Merge(m, src)
}
func (m *ReturnValue) XXX_Size() int {
	return xxx_messageInfo_ReturnValue.Size(m)
}
func (m *ReturnValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnValue.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnValue proto.InternalMessageInfo

func (m *ReturnValue) GetPeriod() int64 {
	if m != nil && m.Period != nil {
		return *m.Period
	}
	return 0
}

func (m *ReturnValue) GetErr() string {
	if m != nil && m.Err != nil {
		return *m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*InputValue)(nil), "checkpoint.InputValue")
	proto.RegisterType((*ReturnValue)(nil), "checkpoint.ReturnValue")
}

func init() {
	proto.RegisterFile("generated.proto", fileDescriptor_e6ed858329eb171d)
}

var fileDescriptor_e6ed858329eb171d = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4f, 0xcd, 0x4b,
	0x2d, 0x4a, 0x2c, 0x49, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0xce, 0x48,
	0x4d, 0xce, 0x2e, 0xc8, 0xcf, 0xcc, 0x2b, 0x51, 0xd2, 0xe5, 0xe2, 0xf2, 0xcc, 0x2b, 0x28, 0x2d,
	0x09, 0x4b, 0xcc, 0x29, 0x4d, 0x15, 0xe2, 0xe3, 0x62, 0x0b, 0x48, 0x2d, 0xca, 0xcc, 0x4f, 0x91,
	0x60, 0x54, 0x60, 0xd2, 0x60, 0x16, 0xe2, 0xe7, 0x62, 0x0f, 0xc8, 0x4f, 0xf1, 0x4b, 0xcc, 0x4d,
	0x95, 0x60, 0x52, 0x60, 0xd6, 0xe0, 0x54, 0xd2, 0xe2, 0xe2, 0x0e, 0x4a, 0x2d, 0x29, 0x2d, 0xca,
	0xc3, 0xae, 0x9e, 0x9b, 0x8b, 0x39, 0xb5, 0xa8, 0x48, 0x82, 0x49, 0x81, 0x49, 0x83, 0xd3, 0xc8,
	0x9f, 0x8b, 0x3b, 0x38, 0x35, 0x2f, 0xc5, 0x39, 0xa7, 0xb4, 0xb8, 0x24, 0xb5, 0x48, 0xc8, 0x01,
	0x95, 0x2b, 0xa6, 0x87, 0x70, 0x85, 0x1e, 0xc2, 0x09, 0x52, 0xe2, 0xc8, 0xe2, 0x48, 0x76, 0x29,
	0x31, 0x00, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xdf, 0xba, 0xfc, 0xc9, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SendClusterClient is the client API for SendCluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SendClusterClient interface {
	SendCluster(ctx context.Context, in *InputValue, opts ...grpc.CallOption) (*ReturnValue, error)
}

type sendClusterClient struct {
	cc grpc.ClientConnInterface
}

func NewSendClusterClient(cc grpc.ClientConnInterface) SendClusterClient {
	return &sendClusterClient{cc}
}

func (c *sendClusterClient) SendCluster(ctx context.Context, in *InputValue, opts ...grpc.CallOption) (*ReturnValue, error) {
	out := new(ReturnValue)
	err := c.cc.Invoke(ctx, "/checkpoint.SendCluster/SendCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SendClusterServer is the server API for SendCluster service.
type SendClusterServer interface {
	SendCluster(context.Context, *InputValue) (*ReturnValue, error)
}

// UnimplementedSendClusterServer can be embedded to have forward compatible implementations.
type UnimplementedSendClusterServer struct {
}

func (*UnimplementedSendClusterServer) SendCluster(ctx context.Context, req *InputValue) (*ReturnValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCluster not implemented")
}

func RegisterSendClusterServer(s *grpc.Server, srv SendClusterServer) {
	s.RegisterService(&_SendCluster_serviceDesc, srv)
}

func _SendCluster_SendCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SendClusterServer).SendCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/checkpoint.SendCluster/SendCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SendClusterServer).SendCluster(ctx, req.(*InputValue))
	}
	return interceptor(ctx, in, info, handler)
}

var _SendCluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "checkpoint.SendCluster",
	HandlerType: (*SendClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCluster",
			Handler:    _SendCluster_SendCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "generated.proto",
}
